# Generated by Django 4.2 on 2023-04-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_startphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartPhoto',
        ),
    ]
